baseurl = "http://10.237.111.11:1313"
languageCode = "utf-8"
theme = "hugo-uno"
title = "升升的笔记本"

[params]
description = "路漫漫其修远兮, 吾将上下而求索"
#logo = "/img/naruto.jpg"
cover = "/img/purse.jpg"
#cv = "/mycv"
