baseurl = "http://blog.gaojiasheng.com/"
languageCode = "utf-8"
theme = "anatole"

[params]
title = "升升的NotaBooka"
author = "Gavin Gao"
description = "上下而求索"
logo = "/img/naruto.jpg"
cover = "/img/purse.jpg"
cv = "/mycv"
