# 分类：技术、国学、随笔、管理

baseurl = "https://blog.gavingao.cn"
languageCode = "utf-8"
theme = "anatole"
summaryLength = 1
title = "升升说"

[params]
title = "升升说"
author = "Gavin Gao"
description = "路漫漫其修远兮，吾将上下而求索"
contentratio = 0.70
redirectUrl = "https://blog.gavingao.cn"
favicon = "favicons/"
toc=true
profilePicture = "/img/keep.jpg"
copyright = "Gavin Gao {{ YEAR }}"

singleDateFormat = "Jan 2, 2006"
indexDateFormat = "Jan 2, 2006"
listDateFormat = "Jan 2"

# related posts
relatedPosts = true
numberOfRelatedPosts = 3

# readmore
readMore = false

[permalinks]
'/' = '/post/'

[[params.socialIcons]]
icon = "fa-brands fa-github"
title = "Github"
url = "https://github.com/GaoJiasheng"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:gaojiasheng.him@foxmail.com"


[[params.socialIcons]]
icon = "fa-brands fa-twitter"
title = "twitter"
url = "https://twitter.com/gaojiashenghim"

[params.utterances]
repo = "gaojiasheng/blog-with-hugo"
issueTerm = "title"
theme= "github-light"


[menu]

[[menu.main]]
name = "Home"
identifier = "home"
weight = 100
url = "/"

[[menu.main]]
name = "时间线"
weight = 300
  identifier = "posts"
  url = "/post/"

[markup]
  [markup.highlight]
      lineNos = true
      lineNumbersInTable = false
      noClasses = true
      noHl = false
      style = 'monokai'
      tabWidth = 8