languageCode = "utf-8"
theme = "hugo-uno"
title = "升升的NotaBooka"
baseurl = "http://localhost:1313"

[params]
description = "路漫漫其修远兮"
description2 = "吾将上下而求索"
logo = "/img/naruto.jpg"
cover = "/img/purse.jpg"
cv = "/mycv"
email = "gaojiasheng.him@foxmail.com"
github = "gaojiasheng"
